#ifndef __DATATYPE__
#define __DATATYPE__

enum DataType {
  DATA_TYPE_DWORD,
  DATA_TYPE_WORD,
  DATA_TYPE_WORD_UNSIGNED,
  DATA_TYPE_HWORD,
  DATA_TYPE_HWORD_UNSIGNED,
  DATA_TYPE_BYTE,
  DATA_TYPE_BYTE_UNSIGNED
};

#define ACCESS_TYPE_FETCH 0
#define ACCESS_TYPE_LOAD 1
#define ACCESS_TYPE_STORE 2

#endif
